allowBuilds:
  '@incubateur-ademe/nosgestesclimat': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@sentry/cli': true
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  canvas: true
  core-js: true
  core-js-pure: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  sqlite3: true
  tree-sitter: true
  tree-sitter-json: true
  unrs-resolver: true
