export const subCategories = {
  voiturethermique: {
    '1person': [
      'voiturethermique',
      'voiture-citadine-essence',
      'voiture-citadine-diesel',
      'voiture-compact-essence',
      'voiture-compact-diesel',
      'voiture-berline-essence',
      'voiture-berline-diesel',
      'voiture-grandeberline-essence',
      'voiture-grandeberline-diesel',
    ],
  },
  'voiturethermique+1': {
    '2persons': [
      'voiturethermique+1',
      'voiture-citadine-essence+1',
      'voiture-citadine-diesel+1',
      'voiture-compact-essence+1',
      'voiture-compact-diesel+1',
      'voiture-berline-essence+1',
      'voiture-berline-diesel+1',
      'voiture-grandeberline-essence+1',
      'voiture-grandeberline-diesel+1',
    ],
    '3persons': [
      'voiturethermique+2',
      'voiture-citadine-essence+2',
      'voiture-citadine-diesel+2',
      'voiture-compact-essence+2',
      'voiture-compact-diesel+2',
      'voiture-berline-essence+2',
      'voiture-berline-diesel+2',
      'voiture-grandeberline-essence+2',
      'voiture-grandeberline-diesel+2',
    ],
    '4persons': [
      'voiturethermique+3',
      'voiture-citadine-essence+3',
      'voiture-citadine-diesel+3',
      'voiture-compact-essence+3',
      'voiture-compact-diesel+3',
      'voiture-berline-essence+3',
      'voiture-berline-diesel+3',
      'voiture-grandeberline-essence+3',
      'voiture-grandeberline-diesel+3',
    ],
    '5persons': [
      'voiturethermique+4',
      'voiture-citadine-essence+4',
      'voiture-citadine-diesel+4',
      'voiture-compact-essence+4',
      'voiture-compact-diesel+4',
      'voiture-berline-essence+4',
      'voiture-berline-diesel+4',
      'voiture-grandeberline-essence+4',
      'voiture-grandeberline-diesel+4',
    ],
  },
  voitureelectrique: {
    '1person': [
      'voitureelectrique',
      'voiture-citadine-electrique',
      'voiture-compact-electrique',
      'voiture-berline-electrique',
      'voiture-grandeberline-electrique',
    ],
  },
  'voitureelectrique+1': {
    '2persons': [
      'voitureelectrique+1',
      'voiture-citadine-electrique+1',
      'voiture-compact-electrique+1',
      'voiture-berline-electrique+1',
      'voiture-grandeberline-electrique+1',
    ],
    '3persons': [
      'voitureelectrique+2',
      'voiture-citadine-electrique+2',
      'voiture-compact-electrique+2',
      'voiture-berline-electrique+2',
      'voiture-grandeberline-electrique+2',
    ],
    '4persons': [
      'voitureelectrique+3',
      'voiture-citadine-electrique+3',
      'voiture-compact-electrique+3',
      'voiture-berline-electrique+3',
      'voiture-grandeberline-electrique+3',
    ],
    '5persons': [
      'voitureelectrique+4',
      'voiture-citadine-electrique+4',
      'voiture-compact-electrique+4',
      'voiture-berline-electrique+4',
      'voiture-grandeberline-electrique+4',
    ],
  },
  voiturehybride: {
    '1person': [
      'voiturehybride',
      'voiture-citadine-hybride',
      'voiture-citadine-hybriderechargeable',
      'voiture-compact-hybride',
      'voiture-compact-hybriderechargeable',
      'voiture-berline-hybride',
      'voiture-berline-hybriderechargeable',
      'voiture-grandeberline-hybride',
      'voiture-grandeberline-hybriderechargeable',
    ],
  },
  'voiturehybride+1': {
    '2persons': [
      'voiturehybride+1',
      'voiture-citadine-hybride+1',
      'voiture-citadine-hybriderechargeable+1',
      'voiture-compact-hybride+1',
      'voiture-compact-hybriderechargeable+1',
      'voiture-berline-hybride+1',
      'voiture-berline-hybriderechargeable+1',
      'voiture-grandeberline-hybride+1',
      'voiture-grandeberline-hybriderechargeable+1',
    ],
    '3persons': [
      'voiturehybride+2',
      'voiture-citadine-hybride+2',
      'voiture-citadine-hybriderechargeable+2',
      'voiture-compact-hybride+2',
      'voiture-compact-hybriderechargeable+2',
      'voiture-berline-hybride+2',
      'voiture-berline-hybriderechargeable+2',
      'voiture-grandeberline-hybride+2',
      'voiture-grandeberline-hybriderechargeable+2',
    ],
    '4persons': [
      'voiturehybride+3',
      'voiture-citadine-hybride+3',
      'voiture-citadine-hybriderechargeable+3',
      'voiture-compact-hybride+3',
      'voiture-compact-hybriderechargeable+3',
      'voiture-berline-hybride+3',
      'voiture-berline-hybriderechargeable+3',
      'voiture-grandeberline-hybride+3',
      'voiture-grandeberline-hybriderechargeable+3',
    ],
    '5persons': [
      'voiturehybride+4',
      'voiture-citadine-hybride+4',
      'voiture-citadine-hybriderechargeable+4',
      'voiture-compact-hybride+4',
      'voiture-compact-hybriderechargeable+4',
      'voiture-berline-hybride+4',
      'voiture-berline-hybriderechargeable+4',
      'voiture-grandeberline-hybride+4',
      'voiture-grandeberline-hybriderechargeable+4',
    ],
  },
  magasin: {
    foot: ['magasindouce', 'magasindouce2kg', 'magasindouce15kg', 'magasindouce30kg'],
    car: ['magasin', 'magasin2kg', 'magasin15kg', 'magasin30kg'],
  },
  clickcollect: {
    foot: ['clickcollectdouce', 'clickcollectdouce2kg', 'clickcollectdouce15kg', 'clickcollectdouce30kg'],
    car: ['clickcollect', 'clickcollect2kg', 'clickcollect15kg', 'clickcollect30kg'],
  },
  livraisondomicile: {
    '': ['livraisondomicile', 'livraisondomicile2kg', 'livraisondomicile15kg', 'livraisondomicile30kg'],
  },
  pointrelais: {
    foot: ['pointrelaisdouce', 'pointrelaisdouce2kg', 'pointrelaisdouce15kg', 'pointrelaisdouce30kg'],
    car: ['pointrelais', 'pointrelais2kg', 'pointrelais15kg', 'pointrelais30kg'],
  },
}
