import { Page } from '@playwright/test'

export const mockRoutesItinerary = async (page: Page) => {
  await page.route(
    'https://photon.komoot.io/api/?q=nan&layer=city&layer=street&layer=house&lang=fr&lat=46.227638&lon=2.213749&zoom=7&location_bias_scale=0.9',
    async (route) => {
      await route.fulfill({
        headers: {
          Etag: 'mocked, because it was run in a E2E environment',
        },
        body: JSON.stringify({
          features: [
            {
              geometry: {
                coordinates: [4.3583709, 47.3734979],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 139563,
                extent: [4.3339065, 47.407652, 4.3842273, 47.3543224],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '21390',
                name: 'Nan-sous-Thil',
                county: "Côte-d'Or",
                state: 'Bourgogne-Franche-Comté',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [6.1834097, 48.6937223],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 52399,
                extent: [6.134292, 48.7092349, 6.2126188, 48.666906],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'city',
                postcode: '54000;54100',
                name: 'Nancy',
                county: 'Meurthe-et-Moselle',
                state: 'Grand Est',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [-1.5541362, 47.2186371],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 59874,
                extent: [-1.6418115, 47.2958583, -1.4788443, 47.1805856],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'city',
                postcode: '44000;44100;44200;44300',
                name: 'Nantes',
                county: 'Loire-Atlantique',
                state: 'Pays de la Loire',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [0.9858037, 45.4079567],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 1861591,
                extent: [0.9510603, 45.4314018, 1.0131022, 45.3884164],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '24800',
                name: 'Nanthiat',
                county: 'Dordogne',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [0.9449856, 45.4134464],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 1861519,
                extent: [0.933278, 45.4548418, 0.989606, 45.3925432],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '24800',
                name: 'Nantheuil',
                county: 'Dordogne',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [2.2071267, 48.8924273],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 85799,
                extent: [2.169302, 48.9205991, 2.234232, 48.874229],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'town',
                postcode: '92000',
                name: 'Nanterre',
                county: 'Hauts-de-Seine',
                state: 'Île-de-France',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [3.3014346, 44.0225739],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 77526,
                extent: [3.2246307, 44.0925108, 3.3528511, 43.9482384],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '12230',
                name: 'Nant',
                county: 'Aveyron',
                state: 'Occitanie',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [0.2195134, 45.8444645],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 1283531,
                extent: [0.2020858, 45.8559374, 0.2427592, 45.8332976],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '16230',
                name: 'Nanclars',
                county: 'Charente',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [118.7915619, 32.0615513],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 2131524,
                extent: [118.3345905, 32.615778, 119.2395068, 31.2267477],
                country: 'Chine',
                osm_key: 'place',
                countrycode: 'CN',
                osm_value: 'city',
                name: 'Nankin',
                state: 'Jiāngsū',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [5.6058987, 46.1534255],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 140520,
                extent: [5.5719334, 46.1791864, 5.6436495, 46.1185057],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '01130;01460',
                name: 'Nantua',
                county: 'Ain',
                state: 'Auvergne-Rhône-Alpes',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [2.564017, 48.5813635],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 80160,
                extent: [2.5182203, 48.5975265, 2.577132, 48.5657104],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '77176',
                name: 'Nandy',
                county: 'Seine-et-Marne',
                state: 'Île-de-France',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [1.1750992, 46.0096593],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 117440,
                extent: [1.1405644, 46.0489282, 1.2093096, 45.9673219],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '87140',
                name: 'Nantiat',
                county: 'Haute-Vienne',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [4.7594, 47.03224],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 129331,
                extent: [4.7361921, 47.0504057, 4.7788481, 47.018509],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '21190',
                name: 'Nantoux',
                county: "Côte-d'Or",
                state: 'Bourgogne-Franche-Comté',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [5.42404, 46.7409],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 147886,
                extent: [5.3992512, 46.7742228, 5.4440313, 46.7269961],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '39140',
                name: 'Nance',
                county: 'Jura',
                state: 'Bourgogne-Franche-Comté',
                type: 'city',
              },
            },
            {
              geometry: {
                coordinates: [-0.4916358, 45.8708393],
                type: 'Point',
              },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 154580,
                extent: [-0.5169889, 45.8787925, -0.4498609, 45.8419299],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '17770',
                name: 'Nantillé',
                county: 'Charente-Maritime',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
          ],
          type: 'FeatureCollection',
        }),
      })
    }
  )
  await page.route(
    'https://photon.komoot.io/api/?q=ang&layer=city&layer=street&layer=house&lang=fr&lat=46.227638&lon=2.213749&zoom=7&location_bias_scale=0.9',
    async (route) => {
      await route.fulfill({
        headers: {
          Etag: 'mocked, because it was run in a E2E environment',
        },
        body: JSON.stringify({
          features: [
            {
              geometry: { coordinates: [-118.242766, 34.0536909], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 207359,
                extent: [-118.6681779, 34.337306, -118.1552983, 33.659541],
                country: "États-Unis d'Amérique",
                osm_key: 'place',
                countrycode: 'US',
                osm_value: 'city',
                name: 'Los Angeles',
                county: 'Los Angeles',
                state: 'Californie',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [-0.5515588, 47.4739884], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 178351,
                extent: [-0.6176931, 47.5262993, -0.5082737, 47.4373546],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'city',
                postcode: '49000;49100',
                name: 'Angers',
                county: 'Maine-et-Loire',
                state: 'Pays de la Loire',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [0.1561947, 45.6484505], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 85809,
                extent: [0.0996131, 45.6715827, 0.1904234, 45.6200489],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'town',
                postcode: '16000',
                name: 'Angoulême',
                county: 'Charente',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [1.1380556, 45.4280556], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 145095,
                extent: [1.1160214, 45.4657711, 1.1898414, 45.3989171],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '24270',
                name: 'Angoisse',
                county: 'Dordogne',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [103.85039863467846, 1.3692077999999999], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_id: 824832478,
                extent: [103.8488154, 1.3700816, 103.8529507, 1.368293],
                country: 'Singapour',
                city: 'Singapour',
                countrycode: 'SG',
                postcode: '567752',
                county: 'Central',
                type: 'house',
                osm_type: 'W',
                osm_key: 'railway',
                street: 'Ang Mo Kio Avenue 8',
                district: 'Ang Mo Kio',
                osm_value: 'station',
                name: 'Ang Mo Kio',
              },
            },
            {
              geometry: { coordinates: [103.8495228, 1.3700803], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_id: 7678872567,
                country: 'Singapour',
                city: 'Singapour',
                countrycode: 'SG',
                postcode: '569811',
                county: 'Central',
                type: 'house',
                osm_type: 'N',
                osm_key: 'railway',
                housenumber: '2450',
                street: 'Ang Mo Kio Avenue 8',
                district: 'Ang Mo Kio',
                osm_value: 'station',
                name: 'Ang Mo Kio',
              },
            },
            {
              geometry: { coordinates: [0.1486257, 43.1941942], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 2459554,
                extent: [0.1379351, 43.2114445, 0.1942105, 43.1865348],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '65690',
                name: 'Angos',
                county: 'Hautes-Pyrénées',
                state: 'Occitanie',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [1.9077204, 44.7389115], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 121718,
                extent: [1.8711286, 44.7734716, 1.9245102, 44.727087],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '46120',
                name: 'Anglars',
                county: 'Lot',
                state: 'Occitanie',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [2.5604934, 43.5641169], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 144097,
                extent: [2.5079473, 43.6042053, 2.6763621, 43.4692676],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '81260',
                name: 'Anglès',
                county: 'Tarn',
                state: 'Occitanie',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [-0.0518922, 45.4747002], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 111337,
                extent: [-0.0679209, 45.4905677, -0.0423937, 45.4667721],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '16300',
                name: 'Angeduc',
                county: 'Charente',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [-0.6364929, 45.2117383], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 398942,
                extent: [-0.6794956, 45.2318999, -0.6031048, 45.1926334],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '33390',
                name: 'Anglade',
                county: 'Gironde',
                state: 'Nouvelle-Aquitaine',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [3.8146147, 48.5845375], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 1780612,
                extent: [3.7932308, 48.6038286, 3.8399814, 48.5742331],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '51260',
                name: 'Anglure',
                county: 'Marne',
                state: 'Grand Est',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [2.3291689, 49.3297487], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 419589,
                extent: [2.3154195, 49.3492482, 2.3437767, 49.3205309],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '60250',
                name: 'Angy',
                county: 'Oise',
                state: 'Hauts-de-France',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [2.9338786, 45.9957342], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 124921,
                extent: [2.9081894, 46.0262228, 2.9730577, 45.9774095],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '63410',
                name: 'Saint-Angel',
                county: 'Puy-de-Dôme',
                state: 'Auvergne-Rhône-Alpes',
                type: 'city',
              },
            },
            {
              geometry: { coordinates: [1.2431994, 47.3320432], type: 'Point' },
              type: 'Feature',
              properties: {
                osm_type: 'R',
                osm_id: 280472,
                extent: [1.2152659, 47.3445604, 1.2683459, 47.2837801],
                country: 'France',
                osm_key: 'place',
                countrycode: 'FR',
                osm_value: 'village',
                postcode: '41400',
                name: 'Angé',
                county: 'Loir-et-Cher',
                state: 'Centre-Val de Loire',
                type: 'city',
              },
            },
          ],
          type: 'FeatureCollection',
        }),
      })
    }
  )
  await page.route('/api/callGMap', async (route) => {
    await route.fulfill({
      headers: {
        Etag: 'mocked, because it was run in a E2E environment',
      },
      body: JSON.stringify({ car: 91.021, foot: 87.914, rail: 91.153, plane: 80.69557099482829 }),
    })
  })
}
