export const fldsCategoriesId: Record<number, string> = {
  1: 'fruits',
  2: 'légumes',
  3: 'herbes',
  4: 'pâtes, riz et céréales',
  5: 'pommes de terre et autres tubercules',
  6: 'fruits à coque et graines oléagineuses',
}

export const fldsCategories: Record<string, string> = {
  fraise: 'fruits',
  pomme: 'fruits',
  orange: 'fruits',
  citron: 'fruits',
  ail: 'herbes',
  artichaut: 'légumes',
  asperge: 'légumes',
  betterave: 'légumes',
  blette: 'légumes',
  carotte: 'légumes',
  celeri: 'légumes',
  champignonmorille: 'légumes',
  chou: 'légumes',
  choudebruxelles: 'légumes',
  choufleur: 'légumes',
  concombre: 'légumes',
  courge: 'légumes',
  courgette: 'légumes',
  cresson: 'légumes',
  echalote: 'légumes',
  endive: 'légumes',
  epinard: 'légumes',
  mangue: 'fruits',
  fenouil: 'légumes',
  haricotvert: 'légumes',
  laitue: 'légumes',
  mache: 'légumes',
  navet: 'légumes',
  mais: 'pâtes, riz et céréales',
  oignon: 'légumes',
  panais: 'légumes',
  petitpois: 'légumes',
  poireau: 'légumes',
  poivron: 'légumes',
  potiron: 'légumes',
  radis: 'légumes',
  salsifis: 'légumes',
  topinambour: 'pommes de terre et autres tubercules',
  cassis: 'fruits',
  chataigne: 'fruits à coque et graines oléagineuses',
  clementine: 'fruits',
  pamplemousse: 'fruits',
  coing: 'fruits',
  figue: 'fruits',
  groseille: 'fruits',
  kiwi: 'fruits',
  mandarine: 'fruits',
  melon: 'fruits',
  mure: 'fruits',
  nectarine: 'fruits',
  myrtille: 'fruits',
  noisette: 'fruits à coque et graines oléagineuses',
  noix: 'fruits à coque et graines oléagineuses',
  prune: 'fruits',
  reineclaude: 'fruits',
  rhubarbe: 'fruits',
  peche: 'fruits',
  cerise: 'fruits',
  abricot: 'fruits',
  framboise: 'fruits',
  poire: 'fruits',
  raisin: 'fruits',
  aubergine: 'légumes',
  brocoli: 'légumes',
  tomate: 'légumes',
  ananas: 'fruits',
  banane: 'fruits',
  avocat: 'légumes',
  carambole: 'fruits',
  datte: 'fruits',
  fruitdelapassion: 'fruits',
  grenade: 'fruits',
  kaki: 'fruits',
  noixdecoco: 'fruits à coque et graines oléagineuses',
  pasteque: 'fruits',
}
