#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

echo "hello-------------"

git rev-parse --short HEAD > .sha
git add .sha

# commit_hash=$(git rev-parse --verify HEAD)

# # Write it
# echo -e "commit_hash='$commit_hash'\n"
