export const usageNumeriqueConfig = {
  email: {
    unit: 'email',
    mainUnit: 'minute',
    mainValue: 'email . terminaux . temps écriture',
    mainDivider: 1,
    secondValue: 'email . destinataires',
    device: 'email . appareil',
    network: 'email . transmission . émetteur . réseau',
    type: 'email . taille',
    appareils: ['smartphone', 'tablette', 'ordinateur portable', 'ordinateur et écran'],
    types: [0.075, 1.075, 5.075],
    networks: ['fixe FR', 'mobile FR'],
  },
  visio: {
    unit: 'heure',
    mainUnit: 'heure',
    mainValue: 'visio . durée',
    mainDivider: 60,
    secondValue: 'visio . emplacements',
    device: 'visio . appareil',
    network: 'visio . transmission . réseau',
    type: 'visio . qualité',
    appareils: ['smartphone', 'tablette', 'ordinateur portable', 'ordinateur et écran', 'TV'],
    types: ['audio', 'SD', 'HD'],
    networks: ['fixe FR', 'mobile FR'],
  },
  streaming: {
    unit: 'heure',
    mainValue: 'streaming . durée',
    mainDivider: 60,
    secondValue: '',
    device: 'streaming . appareil',
    network: 'streaming . transmission . réseau',
    type: 'streaming . qualité',
    appareils: ['smartphone', 'tablette', 'ordinateur portable', 'ordinateur et écran', 'TV'],
    types: ['SD', 'HD', 'ultra HD'],
    networks: ['fixe FR', 'mobile FR'],
  },
}
